### ISSUE TITLE
pixart-diffusion-system NOT FOUND

### ISSUE THREAD

**Issue by Kush-al27** [wyysf-98/CraftsMan3D#35]
ValueError                                Traceback (most recent call last)

[/content/CraftsMan3D/craftsman/__init__.py](https://localhost:8080/#) in find(name)
     28             cls_name = name.split(".")[-1]
---> 29             module = importlib.import_module(module_string, package=None)
     30             return getattr(module, cls_name)

5 frames

[/usr/lib/python3.10/importlib/__init__.py](https://localhost:8080/#) in import_module(name, package)
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 

/usr/lib/python3.10/importlib/_bootstrap.py in _gcd_import(name, package, level)

/usr/lib/python3.10/importlib/_bootstrap.py in _sanity_check(name, package, level)

ValueError: Empty module name

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)

[<ipython-input-21-777033d8ac67>](https://localhost:8080/#) in <cell line: 1>()
----> 1 pipeline = CraftsManPipeline.from_pretrained("craftsman3d/craftsman-v1-5", device="cuda:0", torch_dtype=torch.float32)

[/content/CraftsMan3D/craftsman/pipeline.py](https://localhost:8080/#) in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
     61         device = kwargs.get("device", "cuda" if torch.cuda.is_available() else "cpu")
     62         cfg = load_config(config_path)
---> 63         system = craftsman.find(cfg.system_type)(cfg.system)
     64         print(f"Restoring states from the checkpoint path at {ckpt_path} with config {cfg}")
     65         ckpt = torch.load(ckpt_path, map_location=torch.device('cpu'))

[/content/CraftsMan3D/craftsman/__init__.py](https://localhost:8080/#) in find(name)
     30             return getattr(module, cls_name)
     31         except Exception as e:
---> 32             raise ValueError(f"Module {name} not found!")
     33 
     34 

ValueError: Module pixart-diffusion-system not found!

**Comment by wyysf-98** [comment]
Hi, I've confirmed that the application runs correctly on my local environment. To further tackle the issue, could you please provide additional error logs.

**Comment by Kush-al27** [comment]
Hello, thanks for the reply but unfortunately this is all the error that the code gives out and i am also new to this stuff, so please can you tell me where can i look for additional info..!

**Comment by wyysf-98** [comment]
> I followed the steps on your huggingface site, this is the error i got
> 
> Traceback (most recent call last): File "CraftsMan\inference.py", line 5, in pipeline = CraftsManPipeline.from_pretrained("./ckpts/craftsman-v1-5", device="cuda:0", torch_dtype=torch.float32) File "\CraftsMan\craftsman\pipeline.py", line 54, in from_pretrained ckpt_path = hf_hub_download(repo_id=pretrained_model_name_or_path, filename="model.ckpt", repo_type="model") File "anaconda3\envs\CraftsMan\lib\site-packages\huggingface_hub\utils_validators.py", line 106, in _inner_fn validate_repo_id(arg_value) File "anaconda3\envs\CraftsMan\lib\site-packages\huggingface_hub\utils_validators.py", line 154, in validate_repo_id raise HFValidationError( huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './ckpts/craftsman-v1-5'. Use `repo_type` argument if needed.

Hi, you can try to use the below code to replace the line5 to download the ckpt automatically:

```
# load from huggingface model hub
pipeline = CraftsManPipeline.from_pretrained("craftsman3d/craftsman", device="cuda:0", torch_dtype=torch.float32)
```

**Comment by Kush-al27** [comment]
for inference.py i am getting this error

Traceback (most recent call last):
  File "\CraftsMan\inference.py", line 5, in <module>
    pipeline = CraftsManPipeline.from_pretrained("./ckpts/craftsman-v1-5", device="cuda:0", torch_dtype=torch.float32)
  File "\CraftsMan\craftsman\pipeline.py", line 54, in from_pretrained
    ckpt_path = hf_hub_download(repo_id=pretrained_model_name_or_path, filename="model.ckpt", repo_type="model")
  File "\anaconda3\envs\craftsman\lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "anaconda3\envs\craftsman\lib\site-packages\huggingface_hub\utils\_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './ckpts/craftsman-v1-5'. Use `repo_type` argument if needed.

and for gradio_app.py, i get this error
Traceback (most recent call last):
  File "\CraftsMan\gradio_app.py", line 1, in <module>
    import spaces
  File "\anaconda3\envs\craftsman\lib\site-packages\spaces\__init__.py", line 10, in <module>
    from .zero.decorator import GPU
  File "\envs\craftsman\lib\site-packages\spaces\zero\decorator.py", line 21, in <module>
    from .wrappers import regular_function_wrapper
  File "\envs\craftsman\lib\site-packages\spaces\zero\wrappers.py", line 15, in <module>
    from multiprocessing.context import ForkProcess
ImportError: cannot import name 'ForkProcess' from 'multiprocessing.context' (C\anaconda3\envs\craftsman\lib\multiprocessing\context.py)

**Comment by wyysf-98** [comment]
> for inference.py i am getting this error
> 
> Traceback (most recent call last): File "\CraftsMan\inference.py", line 5, in pipeline = CraftsManPipeline.from_pretrained("./ckpts/craftsman-v1-5", device="cuda:0", torch_dtype=torch.float32) File "\CraftsMan\craftsman\pipeline.py", line 54, in from_pretrained ckpt_path = hf_hub_download(repo_id=pretrained_model_name_or_path, filename="model.ckpt", repo_type="model") File "\anaconda3\envs\craftsman\lib\site-packages\huggingface_hub\utils_validators.py", line 106, in _inner_fn validate_repo_id(arg_value) File "anaconda3\envs\craftsman\lib\site-packages\huggingface_hub\utils_validators.py", line 154, in validate_repo_id raise HFValidationError( huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './ckpts/craftsman-v1-5'. Use `repo_type` argument if needed.
> 
> and for gradio_app.py, i get this error
> 
> Traceback (most recent call last): File "\CraftsMan\gradio_app.py", line 1, in import spaces File "\anaconda3\envs\craftsman\lib\site-packages\spaces__init__.py", line 10, in from .zero.decorator import GPU File "\envs\craftsman\lib\site-packages\spaces\zero\decorator.py", line 21, in from .wrappers import regular_function_wrapper File "\envs\craftsman\lib\site-packages\spaces\zero\wrappers.py", line 15, in from multiprocessing.context import ForkProcess ImportError: cannot import name 'ForkProcess' from 'multiprocessing.context' (C\anaconda3\envs\craftsman\lib\multiprocessing\context.py)

Hi, can you use the latest `inference.py` (https://github.com/wyysf-98/CraftsMan3D/blob/main/inference.py), it would works well and will download the ckpt automatically.

**Comment by Kush-al27** [comment]
hey great it worked, but now it says cuda compile is not enabled though i have installed nvcc and cuda toolkit, i want it to run on cpu for now just for the demo later i will see about it 

Traceback (most recent call last):
  File "\CraftsMan\inference.py", line 8, in <module>
    pipeline = CraftsManPipeline.from_pretrained("craftsman3d/craftsman", device="cuda:0", torch_dtype=torch.float32)
  File "\CraftsMan\craftsman\pipeline.py", line 69, in from_pretrained
    system = system.to(device).eval()
  File "\anaconda3\envs\CraftsMan\lib\site-packages\lightning_fabric\utilities\device_dtype_mixin.py", line 55, in to
    return super().to(*args, **kwargs)
  File "l\anaconda3\envs\CraftsMan\lib\site-packages\torch\nn\modules\module.py", line 1173, in to
    return self._apply(convert)
  File "\anaconda3\envs\CraftsMan\lib\site-packages\torch\nn\modules\module.py", line 779, in _apply
    module._apply(fn)
  File "l\anaconda3\envs\CraftsMan\lib\site-packages\torch\nn\modules\module.py", line 779, in _apply
    module._apply(fn)
  File "l\anaconda3\envs\CraftsMan\lib\site-packages\torch\nn\modules\module.py", line 853, in _apply
    self._buffers[key] = fn(buf)
  File "\anaconda3\envs\CraftsMan\lib\site-packages\torch\nn\modules\module.py", line 1159, in convert
    return t.to(
  File "\anaconda3\envs\CraftsMan\lib\site-packages\torch\cuda\__init__.py", line 284, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
